canonical/mysql-operator

src/mysqlsh_helpers.py
[Jira ticket](https://warthogs.atlassian.net/jira/software/c/projects/DPE/boards/390?modal=detail&selectedIssue=DPE-148)
Paulo and I would like to simultaneously work on a class that encapsulates the MySQL operations related to creating and maintaining an InnoDB cluster.
Create a stub class with stubbed methods for the MySQL operations.
- We have determined the split of work offline. We will be refactoring the appropriate methods and add unit tests as required.
n/a
=> Add stub class and methods for MySQL operations

src/mysqlsh_helpers.py
Necessity to have common function to wrap mysqlsh calls
Inherited working code from reactive machine charm (openstack team).
MySQL setup/configuration calls are execute using mysql-shell cli.
There's still no tests, since we need it to work at the same time on different parts of the code.
* Imported code from [openstack machine charm](https://github.com/openstack/charm-mysql-innodb-cluster/blob/d8d1dc0527046cc3dd41f4394575f14e9675f230/src/lib/charm/openstack/mysql_innodb_cluster.py#L1672)
* refactor to add type hints
* refactor to current standard docstrings
=> Add mysqlsh wrapper

.github/workflows/ci.yaml, src/charm.py, src/mysqlsh_helpers.py, templates/mysqld.cnf, tests/unit/test_charm.py, tests/unit/test_mysqlsh_helpers.py
[Jira ticket 1](https://warthogs.atlassian.net/jira/software/c/projects/DPE/boards/390?modal=detail&selectedIssue=DPE-144) and [Jira ticket 2](https://warthogs.atlassian.net/jira/software/c/projects/DPE/boards/390?modal=detail&selectedIssue=DPE-145)
1. We are not creating our users for mysql correctly. Additionally, we are only revoking a subset of the required priveleges for the `root` user
2. MySQL is binding to `127.0.0.1` upon installation of `mysql-server-8.0`. However, InnoDB requires cluster instances to be bound to `0.0.0.0`
3. We have not yet implemented the helper method to create a cluster
4. We have not yet implemented the helper method to add an instance to the cluster
1. MySQL installation creates `root@localhost`. We additionally create `root@%` and `serverconfig@%` …
=> Refactor MySQL users creations + implement cluster creation and addition of instances to cluster

config.yaml, src/charm.py, src/mysqlsh_helpers.py, tests/unit/test_charm.py, tests/unit/test_mysqlsh_helpers.py
- We are only configuring the instance for the leader unit
- We are not attaching labels to instances (and so units in the cluster appear by their `hostname`s). This would cause problems trying to query the status of an instance using mysqlsh since we do not have access to the hostname in the ops framework
- Config keys cannot have `_`s
- The cluster name cannot have characters other than letters, digits and `_`s. Also, the naming is not consistent with the k8s charm
- Configuring all instances, but create cluster only on the leader unit
- Attach labels (unit names) to each instance in the cluster (would appear as `mysql-0` instead of `juju-<hash>-<unit_number>`)
- Use `-`s instead of `_` in config keys and peer relation data keys
- Randomly generate a hash for the cluster name if one is …
=> Modify on_start to create a cluster on the leader unit + minor bugfixes

.github/workflows/ci.yaml, config.yaml, metadata.yaml, src/charm.py, src/mysqlsh_helpers.py, tests/integration/test_charm.py, tests/unit/test_charm.py, tests/unit/test_mysqlsh_helpers.py
[Jira ticket](https://warthogs.atlassian.net/jira/software/c/projects/DPE/boards/390?modal=detail&selectedIssue=DPE-215)
- We can only provision a cluster of one instance (we have not yet implemented the inclusion of additional instances to the InnoDB cluster)
- We are not attaching any storage volumes in the charm's metadata
- We are unable to scale down the cluster correctly
- Add instances to the cluster on the leader unit's `on_<peer>_relation_joined` event
- Attach a storage volume for each unit at path `/var/lib/mysql/` (where MySQL's data is stored)
- Scale down in `storage_detaching` event (utilizing locks provided by the underlying database to ensure that only one instance is scaled down at a time - a requirement to avoid leaving the cluster in a bad state).
To ensure that we …
=> Implement scaling up and down of the InnoDB cluster

actions.yaml, lib/charms/mysql/v0/mysql.py, src/charm.py, src/mysqlsh_helpers.py, tests/integration/helpers.py, tests/unit/test_charm.py, tests/unit/test_mysql.py, tests/unit/test_mysqlsh_helpers.py, tox.ini
Even though vm and k8s charm share a great deal of code on dealing with mysql, there were no library in place.
Task link is [DPE-205](https://warthogs.atlassian.net/browse/DPE-205)
This PR extract the shared code into a library.
The library contains custom exceptions and a abstract class (`MySQLBase`) with the shared domain knowledge.
We choose to implement `MySQLBase` as an abstract class to enforce the implementation of platform specific methods in the subclass, keeping consistency high across both charms.
The figures on the charm library, as from the current features are:
* 16 common methods (being 3 abstract methods)
* 2 additional methods vm specific
* 4 additional methods k8s specific
Testing is done through unit and integration testing that were already in place.
Since this PR does …
=> Shared MySQL charm library

lib/charms/mysql/v0/mysql.py, metadata.yaml, src/charm.py, src/mysqlsh_helpers.py, tests/unit/test_charm.py, tests/unit/test_mysql.py, tests/unit/test_mysqlsh_helpers.py
We are not currently supporting the legacy `db-router` relation. The relation works by first setting some relevant data (see below) on the application leader unit databag, after which the database leader unit also sets some relevant data in its databag. After this exchange of data information, the mysql router charm bootstraps itself and the application is unblocked into using the mysql and mysqlrouter charms.
Implement the legacy `db-router` relation. The charm implements a single (idempotent) `db_router_relation_changed` event handler which then parses and also populates the relevant data to/from the correct databag locations.
Below is an example of an application (keystone) databag inspection for the `db-router` relation:
```
(venv) ubuntu@shayanp-bastion:~/jhack$ python3 jhack.py …
```
=> Implement the legacy db-router relation

.github/workflows/ci.yaml, README.md, lib/charms/mysql/v0/mysql.py, src/relations/db_router.py, tests/integration/test_charm.py, tests/integration/test_db_router.py, tests/integration/test_shared_db.py, tox.ini
- `mysql.get_cluster_primary_address()` returns a `host:port`, while we only need the host
- integration tests for legacy relations are named the same
- the lib patch version needs to be incremented to be able to publish the charm on charmhub
- use `.split(":")[0]` to only get the host
- rename the integration tests
- update the lib patch version
Get charm ready for publish to charmhub
=> Minor fixes; getting ready to publish to charmhub

README.md, lib/charms/mysql/v0/mysql.py, metadata.yaml, src/relations/db_router.py, tests/unit/test_mysql.py
1. For some methods in the `mysql` lib (`configure_mysqlrouter_user` and `create_application_database_and_scoped_user`), the code assumes that the juju leader unit is also the cluster primary. If it is not, the writes for the methods will fail.
2. After the `root` user is created, subsequent usages of `run_mysqlcli_script` need to pass in the `root` user's password
1. Refactor the two methods to direct the writes to the cluster primary.
2. Pass in the `root` user password in `does_mysql_user_exist` method
Fix bug and direct writes to the cluster primary for methods in the mysql lib
=> Direct writes to the cluster primary for methods in mysql lib

src/charm.py, tests/integration/helpers.py
[Issue](https://github.com/canonical/mysql-operator/issues/23)
The above issue is caused by a race condition where the model (and thus cluster) is torn down before being fully initialized. The error trace is encountered when the instance/unit being torn down is not a member of the cluster and is being attempted to be removed from the cluster in the `storage_detached` event handler.
Add guards to not attempt to remove the instance from the cluster if it is not already a member of the cluster.
Add guards to not remove instance from cluster if it is not already a member
=> Add guards to not remove instance from cluster if it is not already a member

lib/charms/mysql/v0/mysql.py
```
unit-mysql-k8s-0: 19:52:19 ERROR unit.mysql-k8s/0.juju-log database-peers:1:   mysqlsh.DBError: MySQL Error (2003): Shell.connect: Can't connect to MySQL server on 'mysql-k8s-1.mysql-k8s-endpoints.dev.svc.cluster.local:3306' (111)
unit-mysql-k8s-0: 19:52:19 WARNING unit.mysql-k8s/0.juju-log database-peers:1: Failed to confirm instance configuration for mysql-k8s-1.mysql-k8s-endpoints.dev.svc.cluster.local with error Cannot set LC_ALL to locale en_US.UTF-8: No such file or directory
verbose: 2022-07-20T18:52:19Z: About to connect to MySQL at: clusteradmin@mysql-k8s-1.mysql-k8s-endpoints.dev.svc.cluster.local
mysqlsh.DBError: MySQL Error (2003): Shell.connect: Can't connect to MySQL server on 'mysql-k8s-1.mysql-k8s-endpoints.dev.svc.cluster.local:3306' (111)
File …
```
=> Avoid printing error trace for warning logs of is_instance_configured_for_innodb

tests/unit/test_relation_mysql_legacy.py
Removed a couple of config default values on previous PR #28 and forgot to replicate change to unit test.
Add config values on unit test.
=> add missing config after removing defaults

.github/workflows/ci.yaml, tests/integration/test_db_router.py
1. We are deploying a HA mysql cluster for the db-router tests
2. We are testing no loss of data with the mysql cluster scale down in the db-router tests (where we have separate tests that test this)
3. The [following error](https://github.com/canonical/mysql-operator/runs/8232907283?check_suite_focus=true) is likely to occur due to a race condition (deploying mysql and mysqlrouter simultaneously, router could be deployed and related to mysql before mysql is deployed)
1. Deploy a cluster with 1 mysql unit
2. Do not test the "no loss of data with the cluster scale down"
3. Refactor to avoid the race condition
Simplify flaky db-router test by reducing number of mysql units
=> Simplify flaky db-router test by reducing number of mysql units

src/charm.py, src/relations/database.py, tests/integration/helpers.py, tests/integration/test_database.py
Ready-only endpoints were not updated if a unit joined or left the cluster.
Check peer relations joined and departed on the relation to manage the update of the endpoints. A special case is the change of leadership that is handled on leader_elected hook.
When adding or removing a unit of MySQL the endpoints were not updated.
Integration tests includes tests to check the correct update of the endpoints.
=> Fix update endpoints

.github/workflows/ci.yaml, lib/charms/mysql/v0/mysql.py, requirements.txt, src/charm.py, src/mysqlsh_helpers.py, tests/integration/helpers.py, tests/integration/test_healing.py, tests/integration/test_tls.py
~~TLS support is blocked due non updated mysql-shell snap~~ - related to [DPE-722](https://warthogs.atlassian.net/browse/DPE-722)
**EDIT** mysql-shell snap is updated on edge channel.
This PR was repurposed to fix integration tests after TLS refactoring
~~Alternate method to install mysql-shell from upstream sources.~~
Using snap from edge channel.
Opportunistic addressed some issues on CI testing.
Test PR to validate integration testing in CI
=> Refactor for newer mysql-shell snap

.github/workflows/ci.yaml
Just add workflow_call to allow usage of referenced `ci.yaml` on `release.yaml`
=> Add workflow_call

src/charm.py, tests/integration/helpers.py, tests/integration/test_healing.py, tox.ini
Fixed primary restart when setting TLS for a single node cluster.
Replicates k8s [PR#110](https://github.com/canonical/mysql-k8s-operator/pull/110) and addresses issue #59 
When rebooting a single node cluster, use `reboot_from_outage` to restore node as primary;
Testing to come in bundle repo.
=> Fix TLS setting for single unit deployment

.github/workflows/ci.yaml, charmcraft.yaml, conftest.py, tests/integration/integration_constants.py, tests/integration/test_database.py, tests/integration/test_db_router.py, tests/integration/test_ha.py, tests/integration/test_healing.py, tests/integration/test_relation_mysql_legacy.py, tests/integration/test_shared_db.py, tests/integration/test_tls.py, tox.ini
1. We have no way of running our suite of integration tests against multiple releases of ubuntu
2. We are not currently supporting `jammy`
3. `ops_test.build_charm` does not support building multiple charm bases
1. Use Github CI matrix to run each integration test against a list of `series`. Additonally, use `pytest_generate_test` to add the `series` passed from `tox` to into each test.
2. Add support for `jammy`
3. Manually run `charmcraft pack` in a subprocess to pack charms and then pick the correct archive file to deploy based on the series
Add base for jammy
=> Add base of jammy

charmcraft.yaml
We added a temporary fix to be able to pack a charm (that involved installing `setuptools` as a binary package). This fix is not needed
Remove fix
Undo temporary fix that downloaded setuptools as a binary
=> Undo temporary fix that downloaded setuptools as a binary

lib/charms/mysql/v0/mysql.py, tests/unit/test_mysql.py
[jira ticket](https://warthogs.atlassian.net/browse/DPE-917)
When running operations against the database while bootstrapping mysqlrouter, the operations are run against the juju leader unit. However, these operations contain writes and the leader unit is not guaranteed to be the cluster primary.
Run the operations against the cluster primary unit.
Run router bootstrap operations against cluster primary rather than leader unit
The below screenshot demonstrates that the fix in this PR resolves the error.
=> Run router bootstrap operations against cluster primary rather than leader unit

lib/charms/mysql/v0/mysql.py, src/charm.py, tests/integration/relations/test_database.py, tests/integration/relations/test_db_router.py, tests/integration/relations/test_relation_mysql_legacy.py, tests/integration/test_tls.py, tests/unit/test_mysql.py
[mysql-k8s PR 138](https://github.com/canonical/mysql-k8s-operator/pull/138) and [mysql-k8s PR 136](https://github.com/canonical/mysql-k8s-operator/pull/136) introduce some code/fixes to the mysql shared charm lib.
Migrate code in the charm lib and bump the lib version
Add methods needed for backups + fix bug when trying to delete user for unit
=> Add methods needed for backups + fix bug when trying to delete user for unit

lib/charms/mysql/v0/mysql.py, src/relations/mysql_provider.py, tests/integration/helpers.py, tests/integration/relations/test_database.py, tests/unit/test_database.py
[DPE-1174](https://warthogs.atlassian.net/browse/DPE-1174)
The `endpoint` field of the `mysql_client` relation is expecting IP addresses (so that external consumers can connect to the database). However, MySQL Group Replication is storing hostnames as member addresses.
Convert the hostnames to IP addresses for the `endpoint` field.
```
shayan@wellington:~ (07:42:47)  $ juju run-action data-integrator/0 get-credentials --wait --format=y
aml
unit-data-integrator-0:
UnitId: data-integrator/0
id: "6"
results:
mysql:
endpoints: 10.201.101.31:3306
password: uCWa9MCBrMUmZRM8Ua7j1T63
read-only-endpoints: 10.201.101.7:3306
username: relation-9
version: 8.0.32-0ubuntu0.22.04.2
ok: "True"
status: completed
timing:
completed: 2023-02-04 12:42:58 +0000 UTC
enqueued: 2023-02-04 12:42:53 +0000 UTC …
```
=> Return IP addresses as endpoints instead of hostnames

requirements.txt, tests/unit/__init__.py
It is a try to increase tests stability.
=> Switch ops 1.5.2 to released 2.0.0

docs/discourse.yaml, docs/documentation_landing.md, docs/tutorial.md
Following Canonical best practices we need to prepare [Diátaxis](https://canonical.com/blog/diataxis-a-new-foundation-for-canonical-documentation) documentations. It is a first part here "Tutorial".
Add initial documentation/tutorial as a part of the current sprint planning.
Add tutorial to the MySQL operator.
=> Add initial tutorial and Discourse landing pages

.github/workflows/ci.yaml, .gitignore, tox.ini
1) sometime tests are lost silently which is hard to detect due to missing visibility.
2) it is nice to show test coverage inside PR to show "achievements" of writing tests.
Show the current test coverage inside the PR to prevent loosing some tests.
GH PR visibility only.
Not necessary to mention.
=> Upload Coverage report to Codecov

lib/charms/mysql/v0/mysql.py, src/relations/mysql_provider.py, tests/unit/test_database.py, tests/unit/test_mysql.py
k8s charm need to patch offline pods labels to avoid then be picked up by kubernetes services selector rule.
k8s uses hostnames by default.
* include `offline` endpoints output
* parametrized IP conversion
=> update endpoints retrival to report offline nodes

lib/charms/mysql/v0/mysql.py, tests/unit/test_mysql.py
The k8s operator introduces a method that checks if an instance is in a "backing up" state (by checking if the instance is in offline_mode and is hidden from mysql-router). This method can also be used in the mysql vm operator.
Move the method into the shared mysql lib
=> Add method to lib that checks if instances exist in backing up state

lib/charms/mysql/v0/mysql.py, src/relations/db_router.py, src/relations/mysql.py, src/relations/shared_db.py, tests/unit/test_db_router.py, tests/unit/test_relation_mysql_legacy.py, tests/unit/test_shared_db.py
Legacy relations are trying to access database (user checking/creation, etc) as soon as the relation starts.
The problem arises when in bundle deployment, the database is still initializing.
Ref. issue is [DPE-1312](https://warthogs.atlassian.net/browse/DPE-1312)
Defer relations {created/changed} handlers execution until database is initialized.
[DPE-1312]: https://warthogs.atlassian.net/browse/DPE-1312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix early legacy relations handling

.github/workflows/ci.yaml, charmcraft.yaml, tests/integration/conftest.py
We would like to stop support for the `focal` series (as we do not publish it).
Remove `focal` from supported series in charmcraft.py, and adjust the CI to run tests against `jammy` only
=> Deprecate series focal

metadata.yaml
The interface name is using `-`, but naming convention says `_`.
https://juju.is/docs/sdk/styleguide
The endpoint name should use `-`, but interface name `_`.
=> Update peer interface name to follow naming conventions

tests/integration/helpers.py
The test is getting wrong pid due to wide match:
```
> ubuntu@juju-82de18-16:~$ pgrep -a mysqld
> 3774 /snap/charmed-mysql/24/bin/mysqld_exporter ...
> 3996 /bin/sh /snap/charmed-mysql/24/usr/bin/mysqld_safe ...
> 4866 /snap/charmed-mysql/24/usr/sbin/mysqld ...
> ubuntu@juju-82de18-16:~$
> ubuntu@juju-82de18-16:~$ pgrep -a -x mysqld
> 4866 /snap/charmed-mysql/24/usr/sbin/mysqld ...
> ubuntu@juju-82de18-16:~$
```
Use "pgrep -x" for exact match.
=> Use exactly match on 'pgrep mysqld' due to mysqld_exporter availability

tests/integration/relations/test_database.py
The test was waiting not enough for read-only endpoints appearing (5 seconds):
```    
> Traceback (most recent call last):
>   File "/home/runner/work/mysql-operator/mysql-operator/tests/integration/relations/test_database.py", line 278, in test_read_only_endpoints
>     for attempt in AsyncRetrying(stop=stop_after_delay(5), wait=wait_fixed(20)):
>   File "/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/tenacity/_asyncio.py", line 62, in __iter__
>     raise TypeError("AsyncRetrying object is not iterable")
> TypeError: AsyncRetrying object is not iterable
``` 
Waiting for 5 minutes due to slow GH runners.
=> Bump wait for read only endpoints timeout 5 sec -> 5 min in test_database.py::test_read_only_endpoints 

docs/tutorial.md
We used to use locally installed LXD while all other tutorials are migrated to Multipass on Jon request,
Migrate Charmed MySQL VM tutorial to Multipass too.
Also simplify TLS check, update to juju 2.9.42 and improve wording.
=> Switch tutorial from manually installed LXD to Multipass

lib/charms/mysql/v0/mysql.py
As part of [k8s PR 179](https://github.com/canonical/mysql-k8s-operator/pull/179/files), the `configure_instance` method no longer needs the ability to avoid restart of the instance. The lib file was updated in the k8s charm, but not in the vm charm.
Propagate the changes from the k8s charm to the vm charm, and bump the lib version.
=> Refactor configure_instance method to always restart the instance

CONTRIBUTING.md, README.md
The VM README file was not in sync with K8s one and had no endpoints description, causing issues like https://github.com/canonical/mysql-k8s-operator/issues/198
Update README to match the one in mysql K8s repo.
We should consider for the future:
* name endpoints and interfaces identically/similar
* sync amount of interfaces supported by VM and K8s
=> Update README to be in sync with K8s version + update relations/edpoints

metadata.yaml
The charm has old link to bugreport on charmhub: https://github.com/canonical/mysql-operator/issues/54
Updating metada.yaml to use use "summary" and "description" properly.
Also changing style to be in sync with mysql-k8s (and modern formats):
* Reorder relations to show modern one first.
* indicate tls and s3 interfaces as optional.
* add website links
Closes: https://github.com/canonical/mysql-operator/issues/54
see: https://discourse.charmhub.io/t/question-why-charm-mysql-ignores-issues-attribute-in-metadata-yaml/10029
=> Update metadata.yaml to be up-2-date

CONTRIBUTING.md, README.md
Sync README and Contibution guides between VM and K8s.
* Remove Monitoring section from README as we moved it to documentation.
* Update CONTRIBUTING.md to be in sync with other repos.
* Sync README.md layout/wording with MySQL K8s repo.
=> Update README/CONTRIBUTION to follow the common style

lib/charms/mysql/v0/mysql.py, src/mysql_vm_helpers.py, tests/unit/test_mysql.py, tests/unit/test_mysqlsh_helpers.py
[mysql-k8s PR 225](https://github.com/canonical/mysql-k8s-operator/pull/225) requires some changes to the mysql charm lib.
Changes include:
- add timeout to `get_cluster_status` as it is called from update-status and can hang
- use mysql query to `get_member_state` as we've confirmed that the socket file exists before calling it
- add timeout optional kwarg to `_run_mysqlcli_script`
Port over changes to the mysql charm lib
=> DPE-1626 Add timeout kwarg to run_mysqlcli_script, and use timeouts in get_cluster_status

lib/charms/mysql/v0/mysql.py, pyproject.toml, tests/unit/test_backups.py, tests/unit/test_mysql.py
Methods relying on retrieving the cluster primary are doing two or more calls to mysqlsh either through local Popen (vm) or pebble (k8s) with extra overhead.
* use `connect_to_primary` mysqlsh api call that takes care of switching the session to the primary
* consolidate calls that made unnecessary multiple shell calls
_chore_: fixes for unit tests warning removals
=> Optimize mysqlsh calls on library

lib/charms/mysql/v0/mysql.py, src/mysql_vm_helpers.py, tests/integration/helpers.py, tests/integration/high_availability/test_replication.py, tests/unit/test_mysql.py, tests/unit/test_mysqlsh_helpers.py
MySQL `max_connections` is neither being tunned nor being exposed to configuration, staying at the default 151 connections.
Add sane auto-tune strategy while proper configuration management is not implemented.
=> add auto-tuning for max_connections

lib/charms/mysql/v0/backups.py, lib/charms/mysql/v0/mysql.py, src/mysql_vm_helpers.py
1. We are not logging the success or failure of both the `create-backup` and `restore` actions
2. We are currently creating a temp backup and restore directories in the mysql data directory (to ensure that the temp backup directory is on the same volume as the data directory to reduce IOPS latency). However, we expanded the volume to include the snap common directory, so the temp directories no longer need to be in the data directory.
1. Log failures (as warnings) and successes (as info) to the debug log. The failures have prefix `Backup failed`/`Restore failed`, the successes have prefix `Backup successful`/`Restore successful`
2. Move the temp directories out of the data directory, but within the snap common directory (where the volume is mounted). Additionally, make sure that the …
=> DPE-1688 DPE-1913 Add alert logs for success/failure of backups + change temp backup dir

src/charm.py
We are raising an exception when an invalid username is passed to the `get-password` or `set-password` action.
Use `event.fail` to return a more meaningful message (instead of raising an exception).
=> DPE-2061 Fail action to set or get incorrect user password

actions.yaml
The default username is `operation` in the `set-password` and `get-password` action descriptions
Update description to set the default username to `root`
=> DPE-2061 Update default username for set/get password in the description

lib/charms/mysql/v0/mysql.py
During testing, notice that sometimes when an instance is offline the `member_id` in the `performance_schema.group_replication_members` is not set, breaking the method to get instance state and impairing self healing cases.
Refactor method to retrieve state in a more robust fashion.
=> Refactor get_member_state

lib/charms/grafana_agent/v0/cos_agent.py, tests/integration/relations/test_shared_db.py
1. We are deploying keystone `latest/stable` which is way out of date
2. We are wait for active idle where keystone units are constantly in `executing`
1. Use the jammy flavor of `yoga/latest`
2. Use `block_until` units are active, rather than wait for active idle
Closes #258 and closes #259
=> Update keystone charm to yoga/stable in series jammy for shared_db integration test

src/relations/shared_db.py, tests/unit/test_shared_db.py
Mismatch between relation data and server sysvar `wait_timeout`
Use mysqld default `wait_timeout` value.
=> DPE-2215 Fix wait timeout for shared-db

lib/charms/mysql/v0/mysql.py, src/mysql_vm_helpers.py
We are currently not restarting the mysqld exporter when the monitoring user password changes. 
Restart the mysqld exporter (stop and connect again with the new password) when the password changes
=> DPE-2352 Restart mysql exporter upon monitoring password change

lib/charms/mysql/v0/mysql.py, src/charm.py, tests/unit/test_mysql.py
New lib methods for in-place upgrades implemented for k8s not yet in lib.
* Bring methods from k8s [PR#255](https://github.com/canonical/mysql-k8s-operator/pull/255)
* bit of increase on test coverage
=> methods used on in-place upgrades

lib/charms/mysql/v0/mysql.py, src/mysql_vm_helpers.py
- We added a `has_cos_relation` property in a branch in the k8s charm. It seems like this property would be good to have in the vm charm as well as the k8s charm
- Sometimes, we pass the current_event (event of a handler) down a chain of methods before it gets used
- Add `has_cos_relation` property to the MySQLBaseCharm class
- Introduce a `self.current_event` field (initialized to `None`) that can be set on the charm class by an event and then used in helper methods
=> Add `has_cos_relation` to the MySQLCharmBase class

actions.yaml, lib/charms/data_platform_libs/v0/upgrade.py, metadata.yaml, poetry.lock, pyproject.toml, src/charm.py, src/dependency.json, src/mysql_vm_helpers.py, src/upgrade.py, tests/integration/high_availability/test_upgrade.py, tests/unit/test_charm.py, tests/unit/test_upgrade.py
Usage upgrade lib and follow procedure per spec.
Implemented upgrade module, unit test and simple case integration test.
To follow:
* rollback testing
* test with patched snap versions
* discourse doc page
Instructions (happy path):
```shell
git clone git@github.com:canonical/mysql-operator.git
cd mysql-operator
git checkout feature/dpe-1800-in-place-upgrade
charmcraft pack
juju deploy ./*.charm -n 3
juju run-action mysql/leader pre-upgrade-check --wait
juju show-unit mysql/0|yq '.*.relation-info[]|select(.endpoint=="upgrade")'
juju refresh --path ./*.charm mysql
```
=> DPE-1800 in place upgrades

lib/charms/data_platform_libs/v0/upgrade.py, src/charm.py, src/mysql_vm_helpers.py, tests/unit/test_charm.py, tests/unit/test_mysqlsh_helpers.py
We are resetting the workload (wiping the data directory clean and re-initializing mysql) when a recovery (restart of `charmed-mysql` snap) from `unreachable` state is unsuccessful. This is super dangerous and we would like to avoid doing so 
Instead, go to `BlockedStatus` to allow the admin to determine how to best resolve the issue
=> DPE-2214 Avoid resetting workload if recovery from unreachable state unsuccessful

lib/charms/mysql/v0/mysql.py, src/ip_address_observer.py
1, We are producing a lot of logs in `_get_secret_from_juju` (every time we initialize the MySQL helper class)
2. We are not storing the IP address observer PID (but rather the process) in the peer relation databag
1. Only produce logs when actually getting secret from juju secrets backend
2. Store the PID in the peer relation databag
=> DPE-2478 Use actual observer pid in databag + reduce volume of secrets related logs

tests/integration/relations/test_db_router.py
keystone defaults to `latest/stable` which is no more, failing the test_db_router
use the _de facto_ channel
=> set keystone channel

src/charm.py, tests/integration/high_availability/test_upgrade_from_stable.py
The SST test fails because we are taking an action when a unit is offline (we are currently trying to rejoin the instance to the cluster).
Do nothing, as MySQL Group Replication has logic around rejoining an offline instance.
=> Avoid any actions when a unit is offline and allow mysql GR to recover

lib/charms/mysql/v0/mysql.py
By default, `FLUSH LOG` statements are logged to the binlog. When a member is not part of a group (self-healing scenarios), these log statements result in GTID conflicts which prevents the member from self-healing.
Disable logging `FLUSH LOG` statements to the bin log.
=> Avoid logging FLUSH LOG statements to the binlog

.github/workflows/ci.yaml, CONTRIBUTING.md, lib/charms/data_platform_libs/v0/data_interfaces.py, poetry.lock, pyproject.toml, src/relations/mysql_provider.py, tests/conftest.py, tests/integration/helpers.py, tests/integration/relations/test_database.py, tests/integration/test_backups.py, tests/unit/test_backups.py, tests/unit/test_charm.py, tests/unit/test_relation_mysql_legacy.py, tox.ini
`JujuVersion.has_secrets` have to be correctly patched so that secrets-related code would be invoked
Pytest fixtures ensuring the usage to `JujuVersion.has_secrets` (instead of its default behavior returning `False` all way through)
***NOTE***: The 3 pipeline failures are unrelated to secrets. They will be addressed in upcoming PRs as below.
This PR will be merged AFTER those.
- self-healing test failures will be fixed in https://github.com/canonical/mysql-operator/pull/334
- upgrade test failures will be fixed after https://github.com/canonical/mysql-operator/pull/331
=> [DPE-2651] Juju3 pipelines / Testing secrets

templates/logrotate.j2
We are using `-%V_%H%M` as the dateformat for logrotate - this causes filename conflicts after a day of uptime due to file name conflicts.
Use `-%Y%m%d_%H:%M` as the dateformat (for consistency with pgbouncer)
`-%u` in the dateformat does not get correctly substituted as per the docs:
```
error: destination /var/log/mysql/archive_general/general.log-%u_1637 already exists, skipping rotation
root@mysql-k8s-0:/# ls -la /var/log/mysql/archive_error/
total 8
drwxrwx--- 2 mysql mysql 4096 Nov 30 16:37 .
drwxr-xr-x 1 mysql mysql 4096 Nov 30 16:37 ..
-rw-r----- 1 mysql mysql    0 Nov 30 16:36 error.log-%u_1637
```
=> [DPE-3063] Change dateformat in logrotate config to avoid causing filename conflicts after 24hrs of uptime

src/mysql_vm_helpers.py, src/upgrade.py, tests/unit/test_upgrade.py
1. We are not setting up logrotate's cron and config files when we upgrade from the previous stable (which does not have logrotate implemented)
2. Everyday, at midnight, the cron job running logrotate for us conflicts with the logrotate run by logrotate's systemd time
1. Set up cron and logrotate config files when upgrade_granted
2. Change cron to avoid running at midnight
=> Set up logrotate when upgrading + account for logrotate's systemd timer

lib/charms/mysql/v0/s3_helpers.py, tests/unit/test_backups.py
=> Add support for s3 tls-ca-chain

lib/charms/mysql/v0/s3_helpers.py, tests/unit/test_s3_helpers.py
backup fail due to dict key error
- avoid KeyError when no ca chain
- Increase coverage
Fixes #402
=> DPE-3688 fix KeyError when no ca-chain

lib/charms/operator_libs_linux/v1/snap.py, lib/charms/operator_libs_linux/v2/snap.py, src/charm.py, src/mysql_vm_helpers.py, tests/unit/test_charm.py
Missing snap aliases (ie using <snap> instead of charmed-msql.<snap>) for better tool usability inside VM.
Heavily inspired by [ticket DPE-2090](https://github.com/canonical/postgresql-operator/pull/170).
Since it is my first PR, here's how I went about testing my changes. Any feedback is appreciated!
```
tox run -e build-wrapper && mv requirements-last-build.txt requirements.txt && charmcraft pack
juju deploy ./mysql_ubuntu-22.04-amd64.charm 
juju ssh mysql/0 bash
snap aliases
```
With output:
```
Command                    Alias        Notes
charmed-mysql.mysql        mysql        manual
charmed-mysql.mysqlrouter  mysqlrouter  manual
charmed-mysql.mysqlsh      mysqlsh      manual
charmed-mysql.xbcloud      xbcloud      manual
charmed-mysql.xbstream     xbstream     manual …
```
=> [DPE-3702] Add snap aliases for MySQL server / Router

lib/charms/data_platform_libs/v0/data_interfaces.py, lib/charms/mysql/v0/mysql.py, src/constants.py
1. We are not correctly initializing some TLS secret keys (e.g. `cert` instead of `certificate`, `cauth` instead of `certificate-authority`)
2. As part of [PR 385](https://github.com/canonical/mysql-operator/pull/385/files), we got rid of the secret fallback keys. However, this is necessary for clients who are upgrading from old versions of the charm (without secrets) to this version of the charm (with secrets) 
1. Correctly initialize the TLS secret keys
2. Re-introduce fallback keys in the framework of the new secrets lib (data_interfaces) (see Jira ticket for link to conversation for more context)
=> [DPE-3705, DPE-3542] Reintroduce fallback keys and fix TLS secrets initialization

lib/charms/operator_libs_linux/v2/snap.py
It's not easily visible from the logs how long it takes for the snap installation to finish.
After https://github.com/canonical/operator-libs-linux/pull/119 being merged, we should update this lib version in order to use the new logging features.
=> [MISC] Update operator_libs_linux library to version 2.5

lib/charms/data_platform_libs/v0/data_interfaces.py, tests/integration/high_availability/test_upgrade_rollback_incompat.py
The rollback test is really flake-y (failed 9 times in a row in https://github.com/canonical/mysql-operator/actions/runs/8883862972/job/24418820238)
There is a ticket to determine the root cause which @paulomach will pick up, but mark the test as unstable until then
=> Mark rollback test unstable

lib/charms/mysql/v0/mysql.py, lib/charms/rolling_ops/v0/rollingops.py, tests/unit/test_async_replication.py, tests/unit/test_backups.py, tests/unit/test_database.py, tests/unit/test_db_router.py, tests/unit/test_relation_mysql_legacy.py, tests/unit/test_shared_db.py, tests/unit/test_upgrade.py
here was a mixup (two prs in vm were merged simultaneously, both with libpatch 58 - the release libs from the [first PR failed](https://github.com/canonical/mysql-operator/actions/runs/8822816145/job/24223455067) and the release from the [second PR](https://github.com/canonical/mysql-operator/actions/runs/8838306232/job/24277534541) also failed... but un-atomically published both changes in the same libpatch)
[attempt](https://github.com/canonical/mysql-operator/actions/runs/8894633351/job/24433700055#step:4:78) to increment the libpatch only failed
Decrement libpatch back to 58 (to match published lib in charmhub) so that the next update to this lib does not fail to publish
=> Decrement mysql libpatch from 59 to 58 to match published version on charmhub

poetry.lock, pyproject.toml, src/charm.py, src/hostname_resolution.py, tests/unit/test_backups.py, tests/unit/test_charm.py, tests/unit/test_hostname_resolution.py
MAAS deployment fails due hostname resolving to localhost.
Refactor hostname resolution code to remove offending line in `/etc/hosts`
Simplified code and added unit tests.
Fix validated on MAAS@GCP
Fixes #443 #366
=> DPE-3115 Fix MAAS deployment

src/charm.py, src/upgrade.py, tests/unit/test_upgrade.py
* on upgrade, config file was not being update/override in the process
* after updgrade, config change was triggering restart of the service
* restart hook failed to consider all units
This was causing the failure of scaling up after a successful upgrade.
* addressed issues above
=> DPE-4273 avoid restart being triggered after upgrade

.github/workflows/ci.yaml
We are running tests agains outdated Juju versions 2.9.46/3.1.7.
Update tests to use the latest Juju versions 2.9.49/3.1.8.
=> DPE-4556 Bump Juju version to the lastest patchset level of 2.9/3.1

tests/integration/high_availability/test_async_replication.py
Async test missing a wait-for-idle for replica cluster, making test flaky
Add it as done on k8s
=> missing wait on async test

actions.yaml, lib/charms/mysql/v0/async_replication.py, tests/integration/high_availability/test_async_replication.py
`cluster-set-name` as parameter to `promote-to-primary` action is not in accordance with the spec.
Remove the action parameter
=> DPE-4677 Remove parameter not in spec

lib/charms/mysql/v0/async_replication.py, lib/charms/mysql/v0/mysql.py, tests/unit/test_async_replication.py, tests/unit/test_mysql.py
1. Slow status update on switchover
1. Endpoint being empty breaks related router
1. cluster name clash workaround use meaningless hash
* propagating switchover status change across cluster
* use global cluster set primary on standby endpoint
* use model_uuid to workaround cluster name clash (instead of generated uuid)
=> DPE-4658 global-primary on endpoint

.github/workflows/ci.yaml, lib/charms/mysql/v0/async_replication.py, lib/charms/mysql/v0/mysql.py, src/charm.py, tests/integration/helpers.py, tests/unit/test_async_replication.py, tests/unit/test_charm.py, tests/unit/test_db_router.py, tests/unit/test_relation_mysql_legacy.py, tests/unit/test_shared_db.py
We refactored how we calculate `cluster_initialized` and `unit_initialized` in #482. This uses the metadata in the database instead of relying on `units-added-to-cluster` and `unit-intialized` values in the databag. However, there are still places in the code where we set these keys
Remove statements that set these keys
=> Remove unused key/values from the databag

lib/charms/mysql/v0/mysql.py, lib/charms/mysql/v0/tls.py, poetry.lock, tests/unit/test_mysql.py
1. We need to break out a method for executing remove_instance commands (changes already in [k8s PR](https://github.com/canonical/mysql-k8s-operator/pull/433)
2. We need to increment the tls lib as there were changes in [PR 482](https://github.com/canonical/mysql-operator/pull/482), but libpatch wasnt updated
1. Port over changes from the k8s PR
2. Increment tls lib's libpatch
=> [DPE-4118] Port mysql lib changes from k8s + increment tls lib for local changes

src/alert_rules/prometheus/metrics_alert_rules.yaml
We would like to import a minimal set of alert rules from the [Awesome Prometheus Alert Rules blog](https://samber.github.io/awesome-prometheus-alerts/rules#mysql)
Import rules (noting slight modifications). Do not include any replication rules as they are not Group Replication related
=> [DPE-2477] Add a minimal set of alert rules from the Awesome Prometheus Alert Rules blog

lib/charms/data_platform_libs/v0/data_interfaces.py, lib/charms/mysql/v0/mysql.py, lib/charms/tempo_k8s/v1/charm_tracing.py, lib/charms/tempo_k8s/v2/tracing.py, poetry.lock, src/mysql_vm_helpers.py, tests/unit/test_mysqlsh_helpers.py
We are leaking passwords when there's an issue creating a backup
Counterpart in K8s charm: 
Modify code to avoid leaks of any passwords when `_execute_command` or `_run_mysqlcli_script` is called
```
unit-mysql-0: 20:16:52 INFO unit.mysql/0.juju-log A backup has been requested on unit
unit-mysql-0: 20:16:52 INFO unit.mysql/0.juju-log Checking if the unit is waiting to start or restart
unit-mysql-0: 20:16:52 INFO unit.mysql/0.juju-log Checking if backup already in progress
unit-mysql-0: 20:16:52 INFO unit.mysql/0.juju-log Checking state and role of unit
unit-mysql-0: 20:16:52 INFO unit.mysql/0.juju-log Uploading content to bucket=mysql-backups-development, path=mysql-test/2024-08-05T20:16:52Z.metadata
unit-mysql-0: 20:16:53 INFO unit.mysql/0.juju-log Running the xtrabackup commands …
```
=> [DPE-4266] Strip passwords from command execute output and tracebacks

lib/charms/tempo_k8s/v1/charm_tracing.py, tests/integration/helpers.py, tests/integration/high_availability/test_self_healing.py
Network cut test: https://github.com/canonical/mysql-operator/actions/runs/10397182320/job/28792633963
Replicate data on restart test: https://github.com/canonical/mysql-operator/actions/runs/10397182320/job/28792634154#step:28:425
Both of the above tests fail on retrieving a cluster primary when the old primary is stopped or cut from the network. The reason for this, I believe, is the usage of `==` to compare units. Despite the `unit` and `unit_excluded` is the same, the unit is not excluded (the condition does not hold true). This is why the tests above fail to get primary from the "old primary unit" which does not have a running mysqld.
Compare unit names instead
=> Stabilize integration tests; avoid using equality for comparison of units and compare unit names instead

lib/charms/mysql/v0/mysql.py, tests/unit/test_mysql.py
When charm checks for `cluster_initialized`, the property checks for cluster
metadata on any of the units. Case the first unit is unreachable (e.g. freeze test)
the call hangs, impairing charm operation for all units (not only the unreachable one).
And that's when the freeze test hangs, specially on k8s, i.e. when the first unit myqsld
is the one being stopped.
Adds a 10s (scientific) timeout to the call.
=> DPE-5210 Add timeout to check call

lib/charms/mysql/v0/mysql.py, tests/unit/test_mysql.py
When upgrading, the new charm will try to check for server "upgradability" using the admin_address/port of an unit not yet upgrade, i.e. it may not yet have the port open.
Use `clusteradmin` user for the upgrade check, as it will default to standard port 3306.
=> DPE-5178 Upgrade fix for admin-address enabled charm

lib/charms/mysql/v0/tls.py
Caught on tests, uncaught exception on unit teardown when related to a TLS operator
Skip TLS reconfiguration on unit teardown
=> DPE-5493 Skip tls reconfiguration on unit teardown

lib/charms/mysql/v0/mysql.py, lib/charms/tempo_k8s/v2/tracing.py, src/config.py, src/mysql_vm_helpers.py, tests/integration/high_availability/high_availability_helpers.py, tests/integration/high_availability/test_upgrade_skip_pre_upgrade_check.py, tests/unit/test_mysql.py
1. `config_change` hook will try to install plugins if configuration diff so indicates, even if plugins files are not available.
2. admin address enabled charms revisions will fail to connect to mysqld case it's not restarted
Case:
`refresh` ran without `pre-upgrade-check` - so snap is not updated (no plugin files) but config changed is triggered.
1. Check for plugin file before try install. Skip if file not found
2. Ensure mysqld restarts on post refresh `config_change` event
=> DPE-5540 Skip plugin install for not file found

lib/charms/mysql/v0/mysql.py, tests/unit/test_mysql.py
Recent PR #518 introduced new method on update status for the k8s charm.
The method calls node_count method that fails on all units if there's one unresponsive unit, causing regression in freeze db tests, due responsive units not being able to relabel pods.
Add timeout on node_count method to avoid hanging due unresponsive unit(s).
=> DPE-5582 Timeout node count query

src/charm.py, tests/integration/high_availability/test_upgrade_skip_pre_upgrade_check.py
1. When rolling back to revisions with subset of known configuration, the unknown keys are wrongly tried to be dynamically set, which will break the rendered config dict.
2. Configuration is not always being persisted to disk
1. Test config keys for existence in rendered config dict before trying to set them.
2. Always persist configuration to disk on config change
Tests to follow once this revision get promoted to stable
=> DPE-5628 Skip set unknown config keys

src/alert_rules/prometheus/metrics_alert_rules.yaml, tox.ini
Alert rule descriptions do not provide much guidance about what actions the user can take.
Improve the descriptions of the COS alert rule expressions where possible.
(Port of [K8s changes](https://github.com/canonical/mysql-k8s-operator/pull/519))
=> [DPE-5659] Update COS alert rules

src/charm.py
Deployment on MAAS failing with failed mysqlsh connection on instance configuration step.
Issue was that MAAS injected `127.0.1.1` loobpack was being removed after mysqld was started, bindind mysqld admin port to this address.
Drop the `127.0.1.1` _before_ start of mysqld, so admin port bind to correct hostname.
=> fix: (DPE-6055) fix regression on maas deployment

lib/charms/mysql/v0/mysql.py, tests/unit/test_mysql.py
```
MySQL  127.0.0.1:33060+ ssl  Py > util.check_for_server_upgrade(options={'outputFormat': 'JSON'})
Traceback (most recent call last):
File "<string>", line 1, in <module>
ValueError: Util.check_for_server_upgrade: Detected MySQL Server version is 8.0.39. MySQL Shell cannot check MySQL server instances for upgrade if they are at a version the same as or higher than the MySQL Shell version.
MySQL  127.0.0.1:33060+ ssl  Py > session.run_sql('select @@version').fetch_all()[0][0].split('-')[0] == shell.version.split()[1]
false
MySQL  127.0.0.1:33060+ ssl  Py > session.run_sql('select @@version').fetch_all()[0][0].split('-')
[
"8.0.39", 
"0ubuntu0.22.04.1"
]
MySQL  127.0.0.1:33060+ ssl  Py > shell.version
Ver 8.0.38 for Linux on x86_64 - for MySQL 8.0.39 (Source distribution)
```
Shell here …
=> Loosen the manual server shell compatibility check to allow for shell 8.0.38 built for 8.0.39

lib/charms/mysql/v0/mysql.py, tests/unit/test_mysql.py
This PR removes unused methods from the `MySQLBase` class.
I have validated that no Canonical project is using any of these methods, by performing an [org-level search](https://github.com/search?q=org%3Acanonical%20%22get_cluster_members_addresses%22%20OR%20%22cluster_set_cluster_count%22&type=code) on GitHub. Please, if you know of any **non-Canonical** project using the `mysql` public library, let me know.
I have bumped up the `mysql` library patch version. Please, let me know whether this is actually necessary.
=> Remove leftover MySQLBase methods

tests/unit/test_mysql.py
This PR increases test coverage for the [MySQLBase class](https://github.com/canonical/mysql-operator/blob/70ba5f907cbf78c66561b37b5bf01cc90c0c4992/lib/charms/mysql/v0/mysql.py), by adding tests to 4 different untested methods.
Extending test coverage is one of the _Software Development_ onboarding tasks.
=> [ONB-1301] Increase MySQLBase test coverage

lib/charms/mysql/v0/mysql.py, src/mysql_vm_helpers.py, src/upgrade.py
This PR adds warning level messages when a _destructive_ action is performed. The definition of _destructive_ seems to be associated with data loss, which I think it can only happen, from user action, whenever they force a primary failover without checking considering the health of such instance.
- Paulo confirmed that this ticket was created to familiarised myself with the codebases.
- Alex referenced this PostgreSQL operator [PR](https://github.com/canonical/postgresql-k8s-operator/pull/753) as the reason behind the need for warnings.
=> [DPE-5711] Add warnings to destructive actions

src/hostname_resolution.py, tests/unit/test_config.py
On environments with multiple interfaces/networks, retrieving IP from a DNS may lead to unreachable address.
Use juju provided bind address for hostname/ip map, instead of DNS returned address.
=> fix: use juju provided ip (DPE-6105)

lib/charms/mysql/v0/architecture.py, tests/unit/test_architecture.py
This PR proposes the creation of a new _MySQL specific_ lib to define all architecture related helpers. So far, it only contains what is necessary to warn a charm user that they are trying to deploy a charm in the wrong architecture (see doc-string).
Once this PR gets approved, I will start adding the check in all MySQL / MySQL-router operators.
- Most of the code proposed was originally created by @lucasgameiroborges in this PostgreSQL K8S [PR](https://github.com/canonical/postgresql-k8s-operator/pull/613).
- Ideally, I would like for all this logic to be moved to [data-platform helpers](https://github.com/canonical/data-platform-helpers), so other charms could use it as well.
=> [DPE-5588] Create architecture helpers lib

lib/charms/mysql/v0/architecture.py
This PR fixes a couple of issues discovered when integrating the _arch mismatch check_ into MySQL charm codebases.
- It makes the [`WrongArchitectureWarningCharm`](https://github.com/canonical/mysql-operator/blob/f1cce241dc11eed4ee31aba2a3cfb638c4c03edb/lib/charms/mysql/v0/architecture.py#L52-L60) class to raise an exception, instead of exiting with error code `0`. As briefly discussed on 11-12-2024 Technical Sync meeting, there is an edge-case where, if the charm user is _refreshing the revision_ to an arch-incompatible one, some events may be lost in the rollback process if the charm just exits.
- It makes the [`is_wrong_architecture`](https://github.com/canonical/mysql-operator/blob/f1cce241dc11eed4ee31aba2a3cfb638c4c03edb/lib/charms/mysql/v0/architecture.py#L63-L86) helper func …
=> [DEP-5588] Fix architecture lib helpers

src/charm.py, tests/integration/helpers.py, tests/integration/test_architecture.py
This PR introduces the usage of the newly created architecture lib (see #560) into the charm itself.
The shape of the integration tests, as well as the helper used to get the built charm in the architecture that mismatches the one of the host itself, have been adapted from the one Lucas created for PostgreSQL-k8s (see [code](https://github.com/canonical/postgresql-k8s-operator/blob/70a96ce33eb0de054b9297e3bd558f6ece54c0b0/tests/integration/test_wrong_arch.py)).
=> [DPE-5588] Check against invalid arch

lib/charms/mysql/v0/mysql.py, src/charm.py, tests/integration/high_availability/test_self_healing.py, tests/unit/test_mysql.py
This PR adds logic to manually re-join a MySQL replica that has gone `OFFLINE`, to the cluster, whenever MySQL 8.0.21+ [auto re-join](https://dev.mysql.com/doc/refman/8.0/en/group-replication-responses-failure-rejoin.html) attempts have been exhausted.
There are edge cases where a MySQL instance that has lost connection to the cluster it originally belong to (i.e. `OFFLINE`), exhaust its automatic retries (by default 3 retries, with 5 mins between each, starting with MySQL 8.0.21). For those cases, a manual re-join should be performed.
=> [DPE-4375] Add cluster manual re-join handler

lib/charms/mysql/v0/s3_helpers.py, tests/unit/test_s3_helpers.py
This PR ports PostgreSQL operator `_construct_endpoint` helper function ([see code](https://github.com/canonical/postgresql-operator/blob/c5c916d41d00849da5ae657cba4c97c46cb3caad/src/backups.py#L229-L249)) , in order to support the specification of the old S3 endpoints format (i.e. `https://s3.amazonaws.com`), stated in the [charm docs](https://charmhub.io/mysql/docs/h-configure-s3-aws).
I decided to port the helper, instead of updating the docs, in order to make MySQL operator support as similar to PostgreSQL operator as possible. If we eventually decide to stop supporting the old S3 endpoints format, we will do so across our repositories, and not across a sub-set of them.
---
Closes issue https://github.com/canonical/mysql-operator/issues/545
=> [DPE-5908] Support old bucket endpoints format

tests/integration/helpers.py, tests/integration/high_availability/test_upgrade_from_stable.py, tests/integration/high_availability/test_upgrade_rollback_incompat.py, tests/integration/high_availability/test_upgrade_skip_pre_upgrade_check.py
This PR cleans up multiple `@amd64_only` markers from the integration tests. There is an ARM64 stable release already.
- Not all `@amd64_only` markers could be removed, as there is no ARM64 MySQL snap breaking compatibility.
- Tests related to _rolling back when incompatibility_ have been improved to actually fail when they do not rollback.
- Tests helper [cluster_name](https://github.com/canonical/mysql-operator/blob/9530600dacc7a4c9c326c9bbf09f6670c245081b/tests/integration/helpers.py#L320-L342) has been removed (unused).
=> [DPE-6523] Remove AMD64-only test markers

tests/integration/high_availability/test_async_replication.py
This PR removes a work-around present in the async-replication tests, to circumvent a bug that old versions of MySQL had, where under continuous write conditions, a _follower_ cluster could not scale up its replicas.
Even if the official [MySQL bug](http://bugs.mysql.com/114624) is not marked as solved, the issue is no longer reproducible on MySQL 8.0.41.
=> [DPE-6666] Remove async-replication test workaround

lib/charms/mysql/v0/mysql.py, src/mysql_vm_helpers.py
There are changes in https://github.com/canonical/mysql-k8s-operator/pull/596/files which need to be ported over
Noticed that we are writing `ALTER USER` SQL queries before we change its permissions (leading to the password to be exposed if the chown command fails)
Port changes
Chown the file first before writing queries to it
=> [DPE-1531] Port changes from K8s PR to avoid --initialize-insecure

tests/integration/helpers.py
```
$ juju debug-log --model=test-upgrade-rollback-incompat-pz5a --level=WARNING --lines=100 --no-tail
ERROR setting --no-tail and --lines not valid
```
Avoid using `juju debug-log --lines --no-tail`. Replace `--lines` with `--limit`
=> Avoid using incompatible juju debug-log options in test helper

.github/workflows/ci.yaml, .github/workflows/release.yaml
This PR follows the example of PostgreSQL operator workflows (see [VM CI](https://github.com/canonical/postgresql-operator/blob/main/.github/workflows/ci.yaml), [K8s CI](https://github.com/canonical/postgresql-k8s-operator/blob/main/.github/workflows/ci.yaml), [VM release](https://github.com/canonical/postgresql-operator/blob/main/.github/workflows/release.yaml) and [K8s release](https://github.com/canonical/postgresql-k8s-operator/blob/main/.github/workflows/release.yaml)), in order to make our GHA workflows smarter. The only different with respect to those, are:
- I have removed the `tests/**` rule, as discussed with Carl in the _SQL Technical Sync_ meeting.
- I have removed the `pyproject.toml` rule, as discussed with Paulo privately over Mattermost.
---
Addresses [this …
=> [MISC] Ignore paths on GHA workflows

lib/charms/mysql/v0/async_replication.py, lib/charms/mysql/v0/backups.py, lib/charms/mysql/v0/mysql.py, src/charm.py, src/relations/mysql_provider.py, src/upgrade.py, tests/integration/spaces/__init__.py, tests/integration/spaces/conftest.py, tests/integration/spaces/test_spaced_db.py, tests/spread/test_spaced_db.py/task.yaml, tests/unit/test_async_replication.py, tests/unit/test_charm_base.py, tests/unit/test_database.py, tests/unit/test_mysql.py
This PR add Juju spaces support to the operator.
The contents have been ported from the PostgreSQL-operator support [PR](https://github.com/canonical/postgresql-operator/pull/857/files).
- In order to keep a centralized logic, the `get_cluster_endpoints` function was moved side-ways within the class hierarchy (`MySQLBase` -> `MySQLCharmBase`), and its argument changed. Therefore, the proposed `mysql`  charm lib is **not compatible** with existing users (i.e. mysql-k8s-operator). A small adaptation will be needed.
- A centralized way to turn juju unit names into mysql instance labels was created (see [method](https://github.com/canonical/mysql-operator/blob/08356d04350e98056a876ba9e5265f146e948481/lib/charms/mysql/v0/mysql.py#L502-L505)).
=> [DPE-7412] Spaces support

lib/charms/mysql/v0/mysql.py
This PR aims to fix an intermittent [error](https://github.com/canonical/mysql-k8s-operator/actions/runs/15968330351/job/45048983537#step:12:715) Paulo Machado and I saw when a multiple-unit cluster is starting.
The symptom is that a specific unit calling the get_cluster_endpoints method (`mysql-k8s-1` from the error trace) is unable to find the key corresponding to another unit (`mysql-k8s-2` from the error trace), within the dictionary of Juju unit labels. The root cause seems to be the time lapse between a MySQL replica instance starting to replicate transactions, and the time where it is fully caught up, time where the custom label gets applied.
=> [DPE-7648] Fix access to not populated instance label

src/charm.py, src/config.py, src/mysql_vm_helpers.py, src/relations/db_router.py, tests/integration/helpers.py, tests/integration/high_availability/high_availability_helpers.py, tests/integration/high_availability/test_async_replication.py, tests/integration/high_availability/test_primary_switchover.py, tests/integration/relations/test_db_router.py, tests/integration/relations/test_shared_db.py
This PR ports the charm operator code to Python 3.10+ syntax.
=> [MISC] Port MySQL operator to Python 3.10+

docs/reference/software-testing.md, lib/charms/mysql/v0/mysql.py, src/charm.py, src/mysql_vm_helpers.py, src/relations/db_router.py, src/relations/mysql.py, src/relations/mysql_provider.py, src/relations/shared_db.py, tests/integration/high_availability/high_availability_helpers.py, tests/integration/relations/test_relation_mysql_legacy.py, tests/integration/roles/__init__.py, tests/integration/roles/test_database_dba_role.py, tests/integration/roles/test_instance_dba_role.py, tests/integration/roles/test_instance_roles.py, tests/spread/test_database_dba_role.py/task.yaml, tests/spread/test_instance_dba_role.py/task.yaml, tests/spread/test_instance_roles.py/task.yaml, tests/unit/test_database.py, tests/unit/test_db_router.py, tests/unit/test_mysql.py, tests/unit/test_mysqlsh_helpers.py, tests/unit/test_relation_mysql_legacy.py, tests/unit/test_shared_db.py
This PR implements the set of predefined roles proposed in [this specification](https://docs.google.com/document/d/1U1tAWx9a7eb0HvdiS7lnSJS8oHqcl6F9PnAoRdcMjmc/edit?tab=t.0).
In addition to the predefined roles proposed to be on sync with PostgreSQL 16 operators, there is an additional one in order to solve a long time standing time debt: `mysqlrouter`. This predefined role is proposed in order to stop treating _mysqlrouter_ as a magic word used to assign `ALL PRIVILEGES` to the created users whose `extra-user-roles` config argument contained such word. That exact name has been chosen to **preserve backwards compatibility**.
- Implemented MySQL lib [function](https://github.com/canonical/mysql-operator/blob/52b2c8fc3367e67fd0cdf750bda61e25b103d0a2/lib/charms/mysql/v0/mysql.py#L2693-L2709) …
=> [DPE-7322] Support predefined roles

.github/workflows/ci.yaml, docs/how-to/monitoring-cos/enable-alert-rules.md, docs/reference/alert-rules.md, src/alert_rules/prometheus/general_rules.yaml, src/alert_rules/prometheus/replication_rules.yaml, tests/alerts/test_general_alerts.yaml, tests/alerts/test_replication_alerts.yaml
The current setup lacks the alerts for Group Replication and the unit tests for sanity checks
The PR introduces a new alert group for Group Replication, restructures the alerts, and creates a CI job to lint and unit test them.
Related: https://github.com/canonical/mysql-k8s-operator/pull/651
=> feat: group replication alerts

docs/explanation/roles.md, lib/charms/mysql/v0/mysql.py, tests/integration/roles/test_database_dba_role.py, tests/unit/test_mysql.py
This PR updates the database-level DBA role naming in order to lift the restriction of having database names limited to 20 characters (down from the 32 character limit that MySQL supports). The agreed approach is to append a two-digit number at the end of the DBA role name, in order to distinguish it from other DBA role whose first set of characters is the same. 
Paulo and I think that using the Juju relation ID is a bad idea. It will heavily trim the space dedicated to the, potentially pruned database name (as relation IDs are several digits long), and introduced consistency issues when relations get broken, and new relations targeting the same database are created.
Instead, we propose the simple approach of incrementing an implicit counter, dictated by the number of roles which the …
=> [DPE-7322] Tweak database DBA role naming

.github/workflows/ci.yaml, .gitignore, docs/how-to/deploy/terraform.md, terraform/main.tf, terraform/outputs.tf, terraform/variables.tf, terraform/versions.tf, tox.ini
This PR tweaks the Terraform modules of the MySQL Server VM substrate, following the[ CC006 specification](https://docs.google.com/document/d/1EG71A2pJ244PQRaGVzGj7Mx2B_bzE4U_OSqx4eeVI1E/edit?tab=t.0), which outlines how to organize Terrraform variables and outputs at the _charm_ level.
From the list of optional input variables:
=> [DPE-7796] Tweak Terraform modules
