README.md
metadata.yaml
tests/integration/application-charm/metadata.yaml

Relation interface name must not include hyphens.
`s/-/_/`

`s/-/_/g` for *new* relation interface names

---

actions.yaml
lib/charms/mysql/v0/mysql.py
src/charm.py
src/constants.py
tests/integration/helpers.py
tests/integration/test_database.py
tests/unit/test_charm.py

Enhancement to add action to rotate admin passwords.
Implementation of actions get_password, set_password
Need an action to manage credentials for various admin passwords.
Integration test added for explicit and silent password rotation scenarios.

Password rotate action implementation.

---

tox.ini

Ported from mysql-k8s-operator.

DPE-1116 Add shellcheck GH Action

---

lib/charms/data_platform_libs/v0/database_provides.py
lib/charms/operator_libs_linux/v0/apt.py
lib/charms/operator_libs_linux/v1/snap.py

We are using outdated libraries which triggers tags 'Libraries: Out of sync' on PRs.
Those libraries provides bugfixes and should be updated.
Updating libraries.

Update charm libraries: apt 7->10, snap 5->7, data_platform_libs 2->3

---

.github/workflows/ci.yaml

We are using old Juju.
Let's use the latest Juju 2.9.

Bump juju from 2.9.29 to 2.9.38 (latest)

---

src/charm.py
src/mysql_vm_helpers.py
tests/unit/test_charm.py

As described in [DPE-1303](https://warthogs.atlassian.net/browse/DPE-1303).
https://warthogs.atlassian.net/browse/DPE-1303?focusedCommentId=202191
Closes #121 
[DPE-1303]: https://warthogs.atlassian.net/browse/DPE-1303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

set `report_host` when hostname resolves to 127.0.1.1

---

src/relations/mysql_provider.py
tests/unit/test_database.py

Just adding the database field in the provider side. This is to follow the interface signature change https://github.com/canonical/charm-relation-interfaces/pull/43

[MISC] Add database field in the provider-side databag

---

lib/charms/operator_libs_linux/v1/snap.py

Red label on PRs are annoying. Fingerscrossed to have Renovate here one day.
Update libraries to the latest versions (snap only).

Update operator_libs_linux/snap.py LIBPATCH 8 -> 9

---

lib/charms/grafana_agent/v0/cos_agent.py
metadata.yaml
requirements.txt
src/charm.py
src/mysql_vm_helpers.py
tests/unit/test_charm.py

[dpe-1661](https://warthogs.atlassian.net/browse/DPE-1661)
We are mounting `/var/snap/charmed-mysql/common/var/lib/mysql` as a volume, but should be mounting the entire common directory.
Change the path

Change storage volume to be mounted to the charmed-mysql common directory

---

.gitignore
lib/charms/mysql/v0/backups.py
lib/charms/mysql/v0/mysql.py
lib/charms/mysql/v0/s3_helpers.py
src/mysql_vm_helpers.py
tests/unit/test_backups.py
tests/unit/test_mysql.py
tox.ini

rework s3 parameters

---

src/mysql_vm_helpers.py

Service was just being started, but not enabled (i.e. survive host restart)
Add enabling flag

Set service as enable

---

config.yaml
lib/charms/mysql/v0/mysql.py
src/charm.py
src/mysql_vm_helpers.py
tests/unit/test_charm.py
tests/unit/test_mysql.py
tests/unit/test_mysqlsh_helpers.py

Cluster set not being setup
Setup cluster set as primary cluster on deployment

DPE-1231 cluster set default setup

---

src/alert_rules/prometheus/metrics_alert_rules.yaml

Same as k8s [PR244](https://github.com/canonical/mysql-k8s-operator/pull/244)

Basic prometheus alert rule

---

lib/charms/mysql/v0/mysql.py

PR#288 failed to bump libpatch

fix: bump libpatch

---

metadata.yaml

Switch maintainers to the DPE mailing list

[MISC] Switch maintainers to the DPE mailing list

---

lib/charms/mysql/v0/mysql.py
tests/unit/test_mysql.py

When reconnecting, `util.check_for_server_upgrade` outputs an info line.
Strip info line when present.

strip info line when present

---

lib/charms/mysql/v0/mysql.py
src/flush_mysql_logs.py
tests/integration/high_availability/test_replication.py
tests/unit/test_mysql.py
tests/unit/test_mysqlsh_helpers.py

Update lib for k8s usage - mitigations for container churn.
Related to k8s [PR#377](https://github.com/canonical/mysql-k8s-operator/pull/377)

DPE-3547 bump floor value for max_connections

---

lib/charms/mysql/v0/async_replication.py

First version of async lib merged with wrong LIBPATCH value 2 (should be 1 to allow publishing).
Fix it by changing the LIBPATCH value to 1.

Fix initial libpatch value

---

lib/charms/mysql/v0/async_replication.py
lib/charms/mysql/v0/backups.py
lib/charms/mysql/v0/mysql.py
lib/charms/mysql/v0/s3_helpers.py
lib/charms/mysql/v0/tls.py
poetry.lock
pyproject.toml
src/charm.py
src/config.py
src/hostname_resolution.py
src/mysql_vm_helpers.py
src/relations/db_router.py
src/relations/shared_db.py
src/upgrade.py
tests/integration/helpers.py
tests/integration/high_availability/high_availability_helpers.py
tests/integration/high_availability/test_async_replication.py
tests/integration/high_availability/test_replication.py
tests/integration/relations/test_database.py
tests/integration/relations/test_relation_mysql_legacy.py
tests/unit/test_charm_base.py
tests/unit/test_db_router.py
tests/unit/test_hostname_resolution.py
tests/unit/test_mysql.py
tests/unit/test_mysqlsh_helpers.py
tests/unit/test_relation_mysql_legacy.py
tox.ini

We would like to use ruff as a linter and formatter
Use ruff. Fix all lint warnings (and bump libpatches after formatting libs)

[DPE-3881] Use ruff as a linter and formatter

---

src/charm.py

Some external hard to replicate bugs (e.g. #466 ) are even hard to debug to lack of useful logs.
(e.g. SQA tests are run with default info log level)
Decreased log level to some key initialization and upgrade steps

DPE-4910 Change key logs from debug->info

---

.github/workflows/ci.yaml

DPE-5625 chore: bump juju versions

---

src/relations/mysql.py

Race condition found on early relation (bundle) with mysql legacy relation testing for cluster primary before bootstrap
Wrap call on try/except, skipping hook.
fixes #623

fix: dpe-6695 fix race on legacy mysql

---

spread.yaml

This PR is a port of the MySQL K8s operator [one](https://github.com/canonical/mysql-k8s-operator/pull/627).

[MISC] Fix: password-less runner auth with spread

---

docs/explanation/logs/audit-logs.md
docs/explanation/security/index.md
docs/how-to/monitoring-cos/enable-alert-rules.md

As part of SSDLC, we are missing specific advisory for event logging
Added text snippet to address event logging advisory.

docs: DPE-8282 Security Event Logging advisory
